#!/usr/bin/env python3
# Author: Kathryn Ann Emblow

import matplotlib.pyplot as plt
import sys
import csv


def graph(x, y, x_label, y_label, title):
    plt.loglog(x, y)
    plt.xlabel(x_label)
    plt.ylabel(y_label)
    plt.title(title)

    plt.legend
    plt.show()


def parse_data(header, data, title):
    y = [int(row[1]) for row in data]
    x = [x for x in range(1, len(y) + 1)]
    x_label = header[0]
    y_label = header[1]
    graph(x, y, x_label, y_label, title)


def main():
    if len(sys.argv) < 2:
        print("Error: No input file\nUsage: python3 graphing.py <path> title=None", file=sys.stderr)
        return
    path = sys.argv[1]

    try:
        with open(path, 'r') as f:
            data = csv.reader(f)
            header = next(data)

            title = f"{sys.argv[1].split("/")[-1]} {header[1]} per {header[0]}"
            if len(sys.argv) == 3:
                title = sys.argv[2].split("=")[1].strip("\"")

            parse_data(header, data, title)

    except FileNotFoundError:
        print(f"Error: {path} not found", file=sys.stderr)

    
if __name__ == "__main__":
    main()